# Generated by Django 6.0.1 on 2026-02-06 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actionlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
            },
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created_patient", "Created Patient"),
                    ("updated_patient", "Updated Patient"),
                    ("created_appointment", "Created Appointment"),
                    ("updated_appointment", "Updated Appointment"),
                    ("cancelled_appointment", "Cancelled Appointment"),
                    ("checked_in", "Checked In Patient"),
                    ("login", "User Login"),
                    ("logout", "User Logout"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="target_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="target_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="actionlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
