# Generated by Django 6.0.1 on 2026-02-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_actionlog_options_actionlog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('created_patient', 'Created Patient'), ('updated_patient', 'Updated Patient'), ('created_appointment', 'Created Appointment'), ('updated_appointment', 'Updated Appointment'), ('cancelled_appointment', 'Cancelled Appointment'), ('checked_in', 'Checked In Patient'), ('doctor_accepted', 'Doctor Accepted Patient'), ('transferred_to_room', 'Transferred To Room'), ('room_accepted', 'Room Accepted Patient'), ('room_transferred', 'Room Transferred Patient'), ('completed_appointment', 'Completed Appointment'), ('login', 'User Login'), ('logout', 'User Logout')], max_length=50),
        ),
    ]
