# Generated by Django 6.0.1 on 2026-02-03 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(choices=[('PL', 'PLANNED'), ('CH_I', 'CHECEKD_IN'), ('CNC', 'CANCELLED')], default='PL', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
