# Generated by Django 6.0.1 on 2026-02-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.IntegerField(default=15),
        ),
    ]
