# Generated by Django 6.0.1 on 2026-02-03 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PL', 'PLANNED'), ('CI', 'CHECKED_IN'), ('CN', 'CANCELLED')], default='PL', max_length=15),
        ),
    ]
