# Generated by Django 6.0.1 on 2026-02-03 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
